---
name: Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-sudo:
    name: Test sudo
    runs-on: ubuntu-latest
    container:
      image: jsii/superchain:1-buster-slim
    steps:
      - name: Run command with sudo
        run: |
          sudo whoami
